name         'adcade-tomcat7'
version      '0.1.0'
summary      'Install Tomcat7 and deploy WebApps'
description  'Install Tomcat7 and deploy WebApps based opentable module'
author       'Yangming Huang'
license      'MIT'
project_page 'https://github.com/Adcade/puppet-tomcat7'
